Node:
  Name: node6
  DataDir: /root/.kardia
  HTTPHost: 0.0.0.0
  HTTPPort: 8545
  HTTPModules:
    - node
    - kai
    - tx
    - account
    - dual
    - neo
  HTTPVirtualHosts:
    - 0.0.0.0
    - localhost
    - "*"
  HTTPCors:
    - "*"
  P2P:
    PrivateKey: 049de018e08c3bcd59c1a21f0cf7de8f17fe51f8ce7d9c2120d17b1f0251b265
    ListenAddress: tcp://0.0.0.0:3000
    MaxPeers: 25
  LogLevel: info           # crit, error, warn, info, debug, trace
  Metrics: 1
MainChain:
  ServiceName: KARDIA
  ChainId: 1
  NetworkId: 10000
  AcceptTxs: 1       # accept tx sync process or not (1 is yes, 0 is no)
  Seeds:
    - c1fe56e3f58d3244f606306611a5d10c8333f1f6@172.20.0.2:3000
    - 7cefc13b6e2aedeedfb7cb6c32457240746baee5@172.20.0.3:3000
    - ff3dac4f04ddbd24de5d6039f90596f0a8bb08fd@172.20.0.4:3000
  ZeroFee: 0          # 0 is no, 1 is yes
  Database:
    Dir: chaindata                           # directory stores leveldb
    Cache: 16                                # cache is used in leveldb
    Handles: 32                              # handles is used in leveldb
    Drop: 1                                  # Specify whether drop database or not (0 is no, 1 is yes)
Debug: # Devnet config for debugging purposes
  Port: ":6000"
